//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGEntregas_Almudena_Ivan
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincias
    {
        public provincias()
        {
            this.clientes = new HashSet<clientes>();
        }
    
        public int id_provincia { get; set; }
        public string nombre_provincia { get; set; }

        public virtual ICollection<clientes> clientes { get; set; }
    }
}
